### ISSUE TITLE
Residual latex in sec_riemann ca. line 425.

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#127]
In sec_riemann.ptx circa line 425 where the summation notation is introduced: There is some residual latex formatting in the pretext , i.e. `` '' and dollar signs for math mode. 

I may get around to making a pull request for this soon, but I'm making a record of it here so it doesn't get forgotten.

**Comment by grady** [comment]
Similar $x$ issue in the Taylor polynomial section in the paragraph after Eqn (4.5.1).

**Comment by sean-fitzpatrick** [comment]
I've fixed these. (PR coming soon.) The second issue is present only in the "modified" Taylor polynomial section.

The "official" APEX calculus introduces Taylor polynomials in the sequences and series section. My institution teaches it in Calculus 1, as an extension of linear approximation. The original version explains the formula for the coefficients using initial value problem language. That doesn't work if you're introducing Taylor polynomials before antiderivatives, so I had to adjust the language.

@Alex-Jordan at some point I will need to be reminded that we can now do paragraph-level versioning.
I should either make a single file that allows for both versions of this section, or maybe remove my version from GitHub tracking, unless @APEXCalculus is open to the idea of officially having an "early Taylor polynomials" version.

**Comment by APEXCalculus** [comment]
I'd rather not have an official early-Taylor-polynomial version. Yet. (How
common is this early introduction to Taylor poly's? Is this because of
Stewart?)

Part of the point of open-source is that we can make changes to suit our
needs/wants. So making changes for your school is more than fine. I don't
want to present too many official options to people, though, and cause
confusion. Yet. Maybe one day if APEX becomes popular enough we can all
quit our day jobs and just maintain various versions of the text
