### ISSUE TITLE
separable

### ISSUE THREAD

**Issue by Alex-Jordan** [APEXCalculus/APEXCalculusPTX#169]
I think there is an error with the second item on the "not separable" list here:

Paragraph 
https://opentext.uleth.ca/apex-video/sec_Separable.html#p-9164

One fix would be to change the 0 to some nonzero number. Maybe that was the intent when this was written, but the wrong number from column 1 was edited?

Why do we define separable as y'=f(x)g(y)? I mean, not just in APEX, but why do calculus textbooks do this in general? (I think I know why, because they already like the form y'=F(x,y).) With my own students I intend to define it as something you can write in the form f(y)y'=g(x), so the two functions are literally the ones to integrate. Is there any interest in changing that standard in APEX? 

And sort of related, do I understand right that this chapter is new to "edition 5"? That edition 4 doesn't have a differential equations intro? I would not propose the above if there was history to preserve. Maybe as a new chapter, it's still up for some pedagogical rewiring.

**Comment by Alex-Jordan** [comment]
Oh I see. In column 1 there is a cos(x) and in column 2 it has changed to cos(y). But that seems to not be enough to make the equation nonseparable.

**Comment by APEXCalculus** [comment]
Yes, you are right in that the non-separable equation is actually
separable, and it can be fixed by changing the constant from 0 to 1.
I suggest using the given equation in the separable side, then changing the
constant to 1 on the non-sep side. It is another example of how
"homogeneous" can be nicer than "nonhomogenous" counterparts, though
students don't know those terms.

The section actually does define separable in the way that you desire. The
" y' = f(y)g(x) " version is given as an alternate definition. Above,
separable eqs are defined as "n(y)y' = m(x)", and through a cursory look
below, it seems that that is the definition used going forward.

I'm not sure anything has been formally determined concerning including DEs
into APEX. Sean (or was it Ross Magi?) wrote this content to fill needs of
his school, and I haven't done much (anything? maybe proof-read at some
time?) with it as my school doesn't introduce DEs in calc (not enough
time). But certainly many/most schools have an interest in covering some
basics and a chapter like this would be useful.

All that to say: we should include DEs into V5. We should determine was
needs we are serving by doing so, then make sure what we include satisfies
those needs.

Greg

**Comment by sean-fitzpatrick** [comment]
There definitely should be  a 1 (or some other nonzero constant) for the one on the right.

This chapter is a PreTeXt translation of what used to be an appendix for APEX v4 Calculus for Quarters. (I think Ross Magi wrote it, and I converted it. I thought he had author credit somewhere but I don't see it, so that should be fixed.)

I think it is common to consider first order ODEs in the form y'=f(x,y), since that gets you directly to slope/direction fields.
You then have the various special cases:
- f(x,y) =  f(y) (autonomous)
- f(x,y) = g(x)h(y) (separable)
- f(x,y) = q(x)-p(x)y (linear)

I don't know if this is worth mentioning, but technically, one does not really "multiply by dx and integrate both sides".

It's actually just a chain rule (or u-sub) statement: g'(x) = f'(y)dy/dx; u=y, so du = (dy/dx)dx.

**Comment by APEXCalculus** [comment]
These sections could probably use another pass through of editing. I
haven't looked at them for a few years now.

Yes, the "split dy/dx up like it's a fraction" bugs me. At least it is
prefaced by qualifier "informal".

**Comment by sean-fitzpatrick** [comment]
Checking now, our book already does a good job of explaining what is happening (formally) in separation of variables.
So the only problem is the fact that the right hand side should not be zero for the one example. Sending a fix momentarily.

@Alex-Jordan if there's anything other than addressing that one error, please reopen this or comment on the imminent pull request.
