### ISSUE TITLE
Error in proof of geometric series convergence

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#173]
In the second case of the proof of convergence/divergence of a geometric series, dealing with |r| >1.
When r < -1, the limit r^n does not exist, since you have an alternating series. Neither that term, nor the partial sums diverge to negative infinity, as claimed. (What happens is that only the odd terms go to negative infinity.)

https://github.com/APEXCalculus/APEXCalculusPTX/blob/76c12cd0de97c17241388e1d0324246824ef2835/ptx/sec_series.ptx#L394-L402

![image](https://user-images.githubusercontent.com/60004/162825067-b10c1c82-4901-4d8f-8e04-fd6da1d57b66.png)

I'm not sure exactly how to rescue the situation easily using the theorems we have available at this point. It might be necessary to prove directly that no limit can exist using the fact that |r|^n diverges to infinity?

**Comment by Alex-Jordan** [comment]
Related, in:

Theorem 9.2.6: Geometric Series Test 
https://opentext.uleth.ca/apex-video/sec_series.html#thm_geom_series

in item 1, it is problematic to not isolate the case where r=1. If there is agreement on that point, then maybe the entire presentation of this theorem should get an overhaul starting with isolating r=1 as a special case.

**Comment by Alex-Jordan** [comment]
Did you follow my link? Regarding r=1, I am referring to the item 1 in the statement of the theorem. Not the items in Grady's list that is within the proof of the theorem.

**Comment by sean-fitzpatrick** [comment]
Ah yes, sorry. Actually, there are two issues there. (I think one of these has come up before; I thought we had adjusted things, but maybe not.)

1. Earlier, we state that the nth partial sum is the sum of the first n terms in the sequence. Since we start at n=0, arguably, the nth partial sum goes up to r^(n-1), not r^n.

2. And yes, we should state that the sum is n, if r=1, and is given by the stated formula otherwise.

**Comment by grady** [comment]
About item 1 in Sean's last message: Would it not be best to change it to state that it's the sum "ending with the n-th term", to avoid such counting issues and associated confusion?

Regarding the need for the proof itself, I think it's valuable to at least have the part where S_n is worked out, since that lets us apply the definitions. But that might be a good place to stop the details and just hand wave the rest.

The r=1 issue gets introduced in the final step where you divide by (1-r) to arrive at the expression for S_n. So as long as you recognize that, the need for the special case is clear.

**Comment by APEXCalculus** [comment]
Sorry, I arrived late to this thread. So here's a bunch of thoughts from
various messages:

1. I left out proofs intentionally. Sean says the geometric series proofs
were added before him; I have no idea where they came from. I could search
old emails but I'll let it pass right now. I'd be happy to see them go.

2. Alex is right in that the nth-partial sum formula should have a special
case for r=1.

3. Indexing the nth-partial sum issue is a pain. It has been broached
before, and I recall all solutions have awkwardness to them.
  - Sequences are defined to start with n=1; there is a first term, then a
second, etc.
  - It would be nice if all series started with i=1. We can easily re-index
any series to do so. The reason we don't is because of geometric series,
which very naturally start at i=0. Hence the definition of series allows
for starting indices other than 1.
  - The sequence of partial sums is a sequence. So it should start with a
first term S_1, etc. Thus we shouldn't just let S_n be "the sum of all
terms to index n."

I think we should rewrite the nth-partial sum formula as
S_n = (1-r^n)/(1-r).
The sum of the first term is always 1 (S_1 = 1).
The sum of the first two terms is (1-r^2)/(1-r) = 1+r = S_2.

I'm open to suggestions on the partial sum issue.


(A note to Greg to revisit this thread: error errata)

**Comment by Alex-Jordan** [comment]
Just checking since discussion is open, but do we want to define geometric series as a series that for sure has first term 1, not arbitrary first term? I know it messes with the simplicity to have terms of the form c r^n.

With students I focus less on the form and promote recognizing when there is a common ratio. And then if it's less than 1 in absolute value, memorize that the sum is (firstTerm)/(1 - ratio). This pays off not only for things like

sum_{n=0}^{∞} 3/4 (1/2)^n

but also for 

sum_{n=0}^{∞} 3/4 (1/2)^(n+8)

and for

sum_{n=-3}^{∞} 3/4 (1/2)^n

It would be a departure, but one could define a geometric series as one whose adjacent terms have a constant ratio and avoid the form being part of the definition. (I suspect one would have to introduce some sort of form for the terms to prove anything though.)

**Comment by sean-fitzpatrick** [comment]
I definitely allow for geometric series with a common factor, or beginning with some power other than 1.
These are good early opportunities for practice with series manipulation, if you want to come up with a formula when the sum starts at some n=k: you can either realize that this is equivalent to factoring out r^k, or to subtracting the terms 1, r, ... , r^(k-1).

Confession: I also let sequences start at n=0. I'm doing enough examples where we use the computer now that I have to accept 0 as a natural number :-)

**Comment by APEXCalculus** [comment]
In the exercises, there is an example of a geometric series with a common
factor (5/2^n is the sequence). We could definitely use more.

I think starting with the definition, as stated, is best. It allows
students to wrap their minds around the differences between geometric and
p-series. I don't mind adding another key idea or something right after the
Theorem on properties of infinite series. The common factor is an
application of that, and then we can generalize into different starting
terms. Then we can move into the Key Idea of Important Series.





(note to Greg: error errata idea for change)

**Comment by sean-fitzpatrick** [comment]
I've made an attempt at fixing this in #193. Please take a look and let me know if any further adjustments should be made.

**Comment by sean-fitzpatrick** [comment]
Closing, since we've merged the relevant PR.
