### ISSUE TITLE
Agreement of verb tenses

### ISSUE THREAD

**Issue by davidfarmer** [APEXCalculus/APEXCalculusPTX#214]
In this item:

List item 
https://opentext.uleth.ca/apex-crc/sec_limits_one_sided.html#lim_DNE_lr

the tense of the verb does not agree with the other two items.
I suggest that the sentence before that list should say:
   "...three ways in which the limit of a function can fail to exist:"
and then change the verb in the first item to "approaches".

I realize this is a minor comment, but I just implemented permalinks to list items,
so I had to make use of it!

**Comment by sean-fitzpatrick** [comment]
Of course, in the meantime, I've broken your link: the `apex-crc` URL was my test run to see if everyone liked the look.
Since it seemed like the answer was yes (or at least, @APEXCalculus calculus liked it!) I'm making it the default.
That means there's no reason to maintain a separate CRC version.

[This link](https://opentext.uleth.ca/apex-standard/sec_limits_one_sided.html#lim_DNE_lr) should work instead.
And yes, it should be changed to present tense.

**Comment by sean-fitzpatrick** [comment]
Resolved by #216
