### ISSUE TITLE
More exercise errata: differential equation undefined for given intial condition

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#220]
[Exercise 14 in the section on separable differential equations](https://opentext.uleth.ca/apex-accelerated/sec_Separable.html#exercise-1524) has the differential equation `y' = \frac{x^2}{1-y^2}` with initial condition `y(0)=1`.

This seems like a very bad choice of initial condition, since it results in division by zero.

It seems that we should either change the initial condition, or change the denominator to `1+y^2`.

**Comment by Alex-Jordan** [comment]
This chapter is only in the PTX version, is that right?

If you separate and integrate, even maybe changing the subtraction to addition, you get:

y ± y^3/3 = x^3/3 + C

Are students supposed to solve that for y, with y isolated? If an implicit equation is an acceptable answer, I might suggest that we edit the instructions to let that be known to the student. I'd hate to see students at this level trying to isolate y in the above.

**Comment by sean-fitzpatrick** [comment]
The section on separable equations makes it reasonably clear that implicit solutions are acceptable.

If you ignore the original form of the equation, you can apply the initial condition, so it's possible to "solve" the problem if you sort of blunder forward and don't worry about the initial setup.

**Comment by Alex-Jordan** [comment]
I know I'm nitpicking, but if an implicit solution is OK, then is function notation itself OK? (Let alone the division by 0.) 

In this example, you get:
y - y^3/3 = x^3/3 + 2/3
3y - y^3 = x^3 + 2

Both (0,1) and (0,-2) are on that curve.

**Comment by sean-fitzpatrick** [comment]
I'm just now getting back to this. I think I'm the one who is nitpicking: this curve has a cusp at (0, 1), which is the problem. We don't discuss things like existence and uniqueness of solutions in this book, but I think we should ensure that y' is defined at the point set by our initial condition. Changing the initial contition to y(0)=-2 would address the issue.

**Comment by sean-fitzpatrick** [comment]
I've got this change ready to go on an errata branch I hope to send for pull request by the end of the day.

**Comment by Alex-Jordan** [comment]
(Catching up on what feels like hundreds of APEX, PTX, Runestone, and WeBWorK threads while I was away for a week.)

My (nitpicking) point here is that `y' = \frac{x^2}{1-y^2}, y(0) = -2` has a solution curve that satisfies `3y - y^3 = x^3 + 2`. But if we write `y(0)` we apparently view `y` as a function of `x` (as opposed to `x` and `y` having some implicit relationship with each other). So then the solution is not the entire curve `3y - y^3 = x^3 + 2`. It is some subset of that curve that passes through `(0,-2)` but not a large enough subset to make the curve no longer be a function.

If implicit curves like `3y - y^3 = x^3 + 2` are the expected answers, I might be suggesting that instead of "solve `y' = \frac{x^2}{1-y^2}, y(0) = -2`", the statement could be something like "find a solution to `y' = \frac{x^2}{1-y^2}` passing through `(0,-2)`".

**Comment by sean-fitzpatrick** [comment]
We could change that language but it would require rewriting the whole section, because this is consistent with what is written in the text.

I'm not sure that discussion of existence and uniqueness of solutions to ODEs, maximal intervals, etc. is within the scope of the textbook. For now the focus is on developing the basic skill of solving a separate equation.
