### ISSUE TITLE
term including math

### ISSUE THREAD

**Issue by davidfarmer** [APEXCalculus/APEXCalculusPTX#23]
I suggest that "term" tags should not typically contain math.

For example, currently ptx/sec_FTC.ptx  line 1314 contains:
   `The <term>average value of<nbsp/> <m>f</m><nbsp/> on <m>[a,b]</m></term>`.

I suggest that only "average value of" should be in the term tags.

One reason is that we may have tools to automatically identify
when a `term` appears in the text.  The math part tends to be a free
parameter, which is difficult to match.

Similarly, sec_def_int.ptx line 370

**Comment by sean-fitzpatrick** [comment]
Good point. I'm going to add a meta-issue with some things to fix globally once edits to Chapter 5 are merged. Remaining Chapter 5 work mostly involves WW problems, and in particular, WW problems containing TikZ code. Not decided on how to fix those yet.

**Comment by sean-fitzpatrick** [comment]
Taking care of this right now.
In some cases, this is resulting in removing the `<term>` tags altogether because I can't think of a better option.
For example:
```
<term>the limit of <m>f(x)</m> as <m>x</m> approaches <m>c</m> from the left is infinity</term>
```
here there are really two terms in play: 'limit', and 'infinity' (and maybe also 'from the left').
But none of these individually really merits highlighting as a term. The phrase as a whole is really the term.
One might reasonably argue that with the terms limit, infinity, etc. already introduced, there is no need for additional term highlighting here.

Another case: there are `<term>` entries for both `continuous at <m>c</m>` and `continuous on <m>I</m>`. The relevant term here is 'continuous'. Once it's been highlighted as term the first time, does it merit further highlighting when it appears again (in the same section) in a modified context?

If so, do we again highlight 'continuous', or do we highlight the modification of the context that made the subsequent definition necessary? (If the latter, we need to allow math in a term, since, for example, we distinguish between the definition of continuity on an open interval and on a closed interval.)

**Comment by davidfarmer** [comment]
A couple thoughts:

The terms are "continuous at" and "continuous on", so that is how I would
mark them up.  Actually, if I were the author I might write

... is "continuous at the point" < m > ...

or

... is "continuous on the interval" < m > ...

I have thoughts on the other cases, but may not be able to reply
again for a while.

**Comment by sean-fitzpatrick** [comment]
I can do that. I'm also making the decision that punctuation belongs *outside* the term tags. I'm seeing it inside in a few places.

**Comment by sean-fitzpatrick** [comment]
There is no longer any math inside a term. Not closing the issue yet in case there is room for improvement in the changes I made.

**Comment by sean-fitzpatrick** [comment]
Since this is a year old and nobody has objected to my changes, I'll close.
