### ISSUE TITLE
Answer section uses Answer too much and has extra numbering

### ISSUE THREAD

**Issue by APEXCalculus** [APEXCalculus/APEXCalculusPTX#258]
A partial cut/paste from a comment in another issue:

The word "Answer" is in the answer section, before each answer, seems unnecessary and excessive. Is there a reason to not remove this? Even for questions with multiple parts it seems there are less verbose ways of listing the answers.

I also find the numbering potentially confusing. In Section 6.4, the problems are just numbered 1, 2, etc. In the Answer section, they are numbered 6.4.1, 6.4.2, etc. I don't think that's necessary. Further, in one of the pdf's you sent earlier, in some sections each problem is identified with 4 numbers (such as 6.1.5.1, for Chapter 6, Section 1, SubSection 5, problem 1).

**Comment by sean-fitzpatrick** [comment]
If we only include answers in the back, and not solutions, you no longer see "Answer" printed in the back matter.

The difference in numbering is due to the fact that some sections have subsections, and some do not. I'm not sure there's an easy fix for this. In the original LaTeX version, you got around this by using "decorative" subsections: instead of starting a subsection with `\begin{subsection}`, which would create additional structure, you used text formatting commands to create the appearance of a subsection title without getting the numbering/structure.

PreTeXt is seemingly not as permissive as LaTeX, and insists that a subsection should be structured as such :-)

I'll see if there is some way to tinker with formatting (@Alex-Jordan any ideas?) but it might be the case that we need to structure sections without subsections somehow. (This is where @davidfarmer will chime in to say this is a bad idea.)

**Comment by sean-fitzpatrick** [comment]
I'm going to first try to set the numbering level so we stop numbering at the subsection level (see [the guide] (https://pretextbook.org/doc/guide/html/publication-file-numbering.html)).

If that doesn't work, one option would be to replace each existing `subsection` with `paragraphs`. That might be closer in style to the original, although I think most of what is currently marked up as a subsection really is a subsection...

**Comment by APEXCalculus** [comment]
I'd be in favor of not numbering subsections, though leaving them in the
PreTeXt is fine. I fully acknowledge that I did a hack in the original with
just using some \textbf{\large ...} type structure that I had to look up
again each time I used it - which I don't think was terribly often.

In my opinion, subsections should really follow outline-structure rules,
such as "if there is an A, there should also be a B." I certainly didn't
follow that structure; I'm sure there are sections with only 1 subsection.
It also seems that if some content is in a subsection, then all content
should be in a subsection (apart from a short introduction, maybe). Going
through and identifying Subsections for all content of all Sections is a
daunting task, not something I'd like to take on soon. But maybe someday.

A feature of PreTeXt is its hyper structure - everything has a place. That
structure doesn't need to be visible at all levels, of course. I'd vote
hiding subsection numbering in the text, and chapter/section/subsection
numbering for answers in the Answer section.  I don't know how hard that is
to do within the PreTeXt structure.

**Comment by sean-fitzpatrick** [comment]
I think what should happen is that the subsections themselves still get a number (in case we need to refer to them), but the subsection number is not used when numbering the contents of that subsection.

I'm not sure if this will work for the exercises though.

**Comment by sean-fitzpatrick** [comment]
I'll also add: there are some sections (like 1.1) where we could change `subsection` to `paragraphs`. We get topic headings ("Identifying when limits don't exist", "Limits of difference quotients") without adding subsections.

But for something like Section 1.6 (limits involving infinity) I think the divisions (vertical asymptotes, indeterminate forms, horizontal asymptotes) are more like subsections. Someone else (hi, David) might have stronger opinions about this than I do.

**Comment by sean-fitzpatrick** [comment]
Anyway, it would take probably less than an hour to clobber all the subsections and replace them with something unstructured. But it'll take 2 minutes (plus build time) to change how numbering works in the publisher file, so I'll try that first.

**Comment by sean-fitzpatrick** [comment]
OK. If I change the setting so that subsections are not numbered, things swing the other way:

Exercise numbering becomes:

- without subsections: 1.1.1, 1.1.2, 1.1.3, ...
- with subsections: 1, 2, 3,... (instead of 1.1.3.1, 1.1.3.2, 1.1.3.3, ....)

I think the best solution will be to use `paragraphs` instead of `subsection` throughout.
This will solve the numbering of exercises. But I will have to re-write 4 or 5 cross-references that currently point to subsections so that they don't require a number.

**Comment by sean-fitzpatrick** [comment]
I'm ready to submit a pull request that changes things to use `paragraphs` instead of `subsection`.

The main downside of doing this is that there is no line break after the title for a `paragraphs` division. I need to experiment to see how I can accomplish this.

**Comment by sean-fitzpatrick** [comment]
I think the pull request in #262 will be the simplest solution to this problem.

Subsections will still have numbers, but we can omit subsections from the table of contents, and #262 ensures that the presence of a subsection doesn't change the way exercises are numbered.

@APEXCalculus if you're ok with this we can merge #262 and close this issue.
