### ISSUE TITLE
Figures mentioned but not there

### ISSUE THREAD

**Issue by davidfarmer** [APEXCalculus/APEXCalculusPTX#29]
Examples 3.1.21 and 3.1.24 each say that something is "graphed in Figure X", but the
knowl shows a table, not a graph.

**Comment by sean-fitzpatrick** [comment]
I caught these this morning. Committed but not pushed on the housekeeping branch.
The wrong xml:id was used in each case.
Also all of the instances of table/title/tabular have been replaced by figure/caption/tabular.

PS: there were some sage plots missing in 3.5 because I forgot to run mbx for that.
Still missing a Mathematica image. It's in the APEX (LaTeX) source as a PDF. Converting to SVG now. (Advice on folder structure for externally created images is welcome.)

**Comment by sean-fitzpatrick** [comment]
This appears to be fixed.
