### ISSUE TITLE
Should \text have spaces?

### ISSUE THREAD

**Issue by davidfarmer** [APEXCalculus/APEXCalculusPTX#7]
\text{ Area }   or  \text{Area}

**Comment by sean-fitzpatrick** [comment]
This probably depends on context.
Yes for
``<me>
     f(x) \text{ and } g(x)
  </me>``
At the end of a line, no need for the trailing space.

**Comment by Alex-Jordan** [comment]
Was there more context to this issue that you can remember?

In general I would not want those spaces. I can maybe think of exceptions, like in an `aligned` if a second equation column is being used to give explanations, you may have something like this: `\text{because }f(x)\text{ is negative.}`

Even then, I'm not sure if it shouldn't be `\text{because $f(x)$ is negative.}` instead.

**Comment by sean-fitzpatrick** [comment]
I think @davidfarmer asked the question because his conversion script puts the spaces in. And then there were some instances of `\text` that did not include the spaces.

I've been trying to adjust as I go. In many places the spaces make sense. In some places they do not, or at least, the trailing space doesn't belong.

One situation where I made a bunch of changes recently (on a branch, but with plans to merge to master) is units in display math. The LaTeX source from @APEXCalculus isn't consistent about putting a space between the quantity and the unit. I'd say about 75% of the time there is no space. But I think the space should be there (and it is when we use `<quantity>` outside of math mode) so I've been adding it in.

On the other hand, some of the machine-converted stuff would have spaces on both sides of the unit. So the source has `<me>....82\text{ft/s}</me>.`, and `<me>...82\text{ ft/s }</me>.`.

The latter doesn't render well: the period gets added after the `</me>` but there's a trailing space.
So the equation ends up looking like: 

> 82 ft/s .

In these cases I've tried to move everything to `82\text{ ft/s}` (leading space, but no trailing space).
I haven't done a systematic search on this though.

**Comment by sean-fitzpatrick** [comment]
In a different thread somewhere, Alex and I discussed this. I think we agreed that in most cases, the answer is no. E.g. `82 \text{ ft/s}` should be `82\,\text{ft/s}`.
(And once there's support for units in math mode, much of this could become moot.)
