### ISSUE TITLE
Format of docinfo/macros

### ISSUE THREAD

**Issue by Alex-Jordan** [APEXCalculus/APEXCalculusPTX#93]
https://github.com/APEXCalculus/APEXCalculusPTX/blob/a8cfe6cb31a012ab1297338d15cabcccdfcf187e/ptx/apex.ptx#L109

There is an assumption in `extract-pg.xsl` that each line of `docinfo/macros` starts with `\newcommand` and is just one macro being defined. I cannot find that "rule" specified in the main documentation, although there is something [here](https://pretextbook.org/doc/guide/html/topic-mathematics.html) in 4.8.12 that says "Keep them simple—one or two arguments, and one-line definitions."

Right now in APEX, a few things are there that don't fit this restriction. Some lines being `\DeclareMathOperator`. Maybe that should be allowed, or maybe this is not necessary because there is an equivalent way to do this with `\newcommand`.

And then there is a large block that begins `%%temporary fix to get circles working right in TexLive 2019`. I think this is maybe out of place. It could go into a `latex.preamble.late` for now.

All this matters because it breaks a PG problem every now and then.

Pinging @rbeezer because maybe we need to discuss clear constraints on `docinfo/macros`.

**Comment by sean-fitzpatrick** [comment]
You can also leave things as is and tell me to smarten up. (I'll admit to not having read the rules for the macros section -- but it was already pretty extensive before I got to it!)

`\DeclareMathOperatorl{}{}` can be replaced by `\newcommand{}{\operatorname{}}`.

And maybe that fix for TikZ belongs in the latex-image-preamble. 

There are two problems with circles in APEX: one is that Greg used a syntax that's now deprecated, but still seems to work (maybe you need to specify a backwards compatibility). The bigger problem: in pgfplots it used to be that if you set a circle to have radius 1, that would be understood as 1 unit with respect to the coordinate system.

But for some reason that shrunk by a factor of 100! I discovered some circles were "missing" because they were so small they couldn't be seen.
I could either edit TikZ source throughout to multiply radii by 100, or add that fix.

Can it live in latex-image-preamble? We need it for building images for html as well as for PDF.

**Comment by Alex-Jordan** [comment]
Is that factor of 100 thing a bug? If you have a chance, I'd be curious if you could cook up a small tex file that demonstrates the issue, and I'd see if it happens on my machine too. We already saw there is some sort of discrepancy with the tikz-euclide stuff.

A solid reason it can't stay where it is, is that everything in `docinfo/macros` will be put into MathJax. I think `latex-image-preamble` sounds right, but I'd be curious to investigate the issue deeper if that hasn't been done yet.

**Comment by sean-fitzpatrick** [comment]
There are two bugs, I think. The first is [this one](https://sourceforge.net/p/pgfplots/bugs/232/), which is what breaks the old syntax for circles in `pgfplots`. 

The fix for having the radius wrong comes from [this stack exchange post](https://tex.stackexchange.com/questions/527727/distorted-circles-in-axis-environment-with-tikz)

Comment there is that a fix is promised but so far not forthcoming. But maybe it's fixed in TeXLive 2020?

**Comment by Alex-Jordan** [comment]
OK, thanks, that helped. I'm not on TL 2020 yet, but maybe soon.

I think part of this will be removing using `circle` in the first place. I searched for where it is used, and the first example I see is in Figure 7.1.2 (c) [here](https://opentext.uleth.ca/apex-standard/sec_ABC.html) to make the little black dots. The "pgfplots" way to do that is to use `\addplot coordinates` to make plotted points. If they should be styled differently from the default, we can have `\addplot[riemanntestpoint] coordinates` or something like that.

**Comment by sean-fitzpatrick** [comment]
The place where I noticed a problem was the figure at line 576 in [limit_analytically](https://github.com/APEXCalculus/APEXCalculusPTX/blob/main/ptx/sec_limit_analytically.ptx)

The unit circle there did not show up at all after upgrading to TeXlive 2019. Adding the "fix" got it back. But maybe there's a better way to code this diagram as well

**Comment by rbeezer** [comment]
> I cannot find that "rule" specified in the main documentation

Not in the documentation, since it is not a rule.  IIRC, and based on review, the code in `extract-pg.xsl` is doing its best to slim down the LaTeX macros to only what is needed for a particular WW problem, rather than acepting a global configuration for each problem.  Motivated by keeping the physical size of a problem file small?  Do we still have limits on base64 strings in URLs?  I think so, but a lot has changed.

Options:

1.  Some new, less-expedient, approach that sits nicely with WW.
2.  Filter `\newcommand` as we do now.  But keep every other significant command, rather than dropping them.

We already scrub lots of (all?) TeX comments.

The "operatorname" device might be a good first item in a list of best practices for the collection of LaTeX macros.  Just like challenges processing "normal" LaTeX, I don't think we can ever make this fool-proof, so author-education would be a good thing to do.  Let's continue on `-dev` if more discussion is needed, with links back-and-forth.

**Comment by Alex-Jordan** [comment]
> The place where I noticed a problem was the figure at line 576 in limit_analytically

I'm probably responsible for making that a pgfplots graph in the first place, circa 2016. But as I look at it now, I would call it a geometry diagram and make it in tikz without pgfplots.

**Comment by sean-fitzpatrick** [comment]
Seems that's possible -- I just checked the original and it doesn't use pgfplots.
There's definitely room to overhaul some of the TikZ but not sure it's high on my priority list.

**Comment by sean-fitzpatrick** [comment]
This seems like an issue we should try to tackle this summer.
Options:
- Leave the TikZ corrections where they are; I notice that we now have a separate set of macros for PG-TikZ and we could scrub it from that part.
- Rewrite all the TikZ code where it's out of date.

The `DeclareMathOperator` part has been taken care of already.

**Comment by sean-fitzpatrick** [comment]
@Alex-Jordan I think this was solved by adding a second latex-image-preamble for PG-TikZ?
Does that change with the move to 2.17?

There is a larger issue of needing a general overhaul/audit of TikZ images. There are the problems noticed by @grady in #161 as well as the fact that there are some images using deprecated TikZ syntax.

**Comment by Alex-Jordan** [comment]
The initial topic of this issue has been resolved by using `\newcommand`. I'm closing, but if there was something else that came up here that is still an issue, we can make a new issue.

**Comment by sean-fitzpatrick** [comment]
It looks like @Alex-Jordan forgot to close this, based on the "I'm closing" comment? I'll close it now.
